#!/usr/bin/env bash
# Ensure the .ssh directory exists
mkdir -p ~/.ssh

# Generate the RSA private key with 4096 bits and passphrase 'betty'
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty" -m PEM
