#!/usr/bin/env bash
#script to automate fix on what is keeping nginx from listening to port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
